version: "3.6"

services:
  #viagem-api:
  #  image: viagem-api:latest
  #  build: 
  #      context: .
  #      dockerfile: src/services/Estudos.Viagem.WebApi/Dockerfile
  #  environment:
  #    ASPNETCORE_ENVIRONMENT: Development
  #    ASPNETCORE_URLS: http://+:5000
  #    ConnectionStrings__RabbitMq: 'amqp://guest:guest@rabbitmq:5672'
  #    ConnectionStrings__SqlServerConnection: 'Server=sqlserver;Database=EstudosMensageriaDb;User Id=sa;Password=Teste@123'
  #  ports:
  #    - "5000:5000"
  #  depends_on:
  #      - rabbitmq
  #      - sqlserver-db

  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

  sqlserver-db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Teste@123"
      ACCEPT_EULA: "Y"

  mongo-db:
    container_name: mongo-db
    image: 'mongo'
    ports:
        - '27017:27017'
    environment:
        MONGO_INITDB_ROOT_USERNAME: 'admin'
        MONGO_INITDB_ROOT_PASSWORD: 'abc123!'