version: "3.6"

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Teste@123"
      ACCEPT_EULA: "Y"

  mongo-db:
    image: 'mongo'
    ports:
        - '27017:27017'
    container_name:  mongo-db
    environment:
        MONGO_INITDB_ROOT_USERNAME: 'admin'
        MONGO_INITDB_ROOT_PASSWORD: 'abc123!'